### ISSUE TITLE
Update `doctrine/lexer`

### ISSUE THREAD

**Issue by misaert** [creof/wkt-parser#13]
Hi,

On `composer.json`, there is `"doctrine/lexer": "~1.0"` but there are now 2 new major versions of this package.

Several packages require at least `doctrine/lexer:^2` like `doctrine/annotations:2.0.1` and `friendsofphp/php-cs-fixer:v3.14.4` require `doctrine/annotations:^2`.

Have you planned to update the dependency of `doctrine/lexer`?

Thanks,

Mickaël

**Comment by axi** [comment]
Please check #14

**Comment by axi** [comment]
This repo has been hard forked here https://github.com/longitude-one/wkt-parser
